Groups treeview incorporated
sourcecoursepoc/sourcecourse_poc pull request #225
Opened 2023-05-22 08:38 UTC by suryacgust90

2023-05-23 13:59 UTC, sourcecoursepoc requested changes

2023-05-23 13:59 UTC, sourcecoursepoc commented on src/components/ComposePage/GroupsPage/ModalBox/groupsModalBox.tsx
> +        console.log('Its getting changed')
Remove unwanted console

2023-05-23 13:59 UTC, sourcecoursepoc commented on src/components/ComposePage/MainContent/mainContent.tsx
> +      projectUid: 2,
Diff between 2 & 3?

2023-05-25 06:20 UTC, suryacgust90 commented on src/components/ComposePage/MainContent/mainContent.tsx
> +      projectUid: 2,
Dynamic projectUid fetch incorporated

2023-05-25 06:22 UTC, suryacgust90 commented on src/components/ComposePage/GroupsPage/ModalBox/groupsModalBox.tsx
> +        console.log('Its getting changed')
Removed unwanted console

2023-05-25 09:06 UTC, sourcecoursepoc approved these changes

2023-05-25 09:06 UTC, merged